/**
 * Generate supabase/seed.sql — a pure-SQL seed of the demo cycle with FIXED
 * UUIDs, for pasting straight into the Supabase SQL editor.
 *
 *   npx tsx scripts/build-seed-sql.mts
 *
 * Source of truth is data/sample_qm_export.xlsx run through the REAL ingest +
 * engine (identical to `npm run seed:supabase`), so item_stats and
 * participant_scores are the genuine computed values, and responses carry
 * answer_given / response_time. UUIDs are derived deterministically (UUIDv5-style
 * over the natural keys) so the file is stable and re-runnable.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { parseExport, ingestAndClean } from "../lib/ingest/index";
import type { CleanResponse } from "../lib/ingest/types";
import { getEngine, ENGINE_VERSION } from "../lib/engine/index";
import type { ItemMeta, ResponseRecord } from "../lib/engine";
import { InMemoryDataProvider } from "../lib/data/in-memory-provider";

const engine = getEngine();

// Deterministic UUIDv5-style id from a namespaced key.
function uuid(key: string): string {
  const h = createHash("sha1").update(`g12pp-seed:${key}`).digest();
  const b = Buffer.from(h.subarray(0, 16));
  b[6] = (b[6]! & 0x0f) | 0x50; // version 5
  b[8] = (b[8]! & 0x3f) | 0x80; // RFC-4122 variant
  const x = b.toString("hex");
  return `${x.slice(0, 8)}-${x.slice(8, 12)}-${x.slice(12, 16)}-${x.slice(16, 20)}-${x.slice(20, 32)}`;
}

// Clean display name (so the app's essay detection / short names work).
function cleanName(raw: string): string {
  if (/[؀-ۿ]/.test(raw) || /arabic/i.test(raw)) return "Arabic as a 1st Language";
  if (/applicable math/i.test(raw)) return "Applicable Math";
  if (/english/i.test(raw)) return "English as a 2nd Language";
  if (/scientific/i.test(raw)) return "Scientific Thinking";
  if (/life/i.test(raw)) return "Life Success Skills";
  return raw;
}

// SQL literal helpers.
const q = (s: string | number | null | undefined): string =>
  s === null || s === undefined ? "NULL" : `'${String(s).replace(/'/g, "''")}'`;
const n = (v: number | null | undefined): string =>
  v === null || v === undefined || Number.isNaN(v) ? "NULL" : String(v);
const enumLit = (s: string | null | undefined): string =>
  s === null || s === undefined ? "NULL" : `'${String(s).replace(/'/g, "''")}'`;

const CYCLE_ID = uuid("cycle:may-2026");
// 0005: fixed year UUID (matches supabase/seed.sql) — the 2026 year the cycle's
// May sitting belongs to.
const YEAR_ID = "20260000-0000-4000-8000-000000002026";

function main() {
  const file = readFileSync("data/sample_qm_export.xlsx");
  const { rows } = parseExport(file);
  const { cleanedResponses } = ingestAndClean(rows);
  const recs = cleanedResponses as CleanResponse[];

  // ── ids ────────────────────────────────────────────────────────────────
  const assessmentNames = [...new Set(recs.map((r) => cleanName(r.assessmentName)))];
  const rawToClean = new Map(recs.map((r) => [r.assessmentName, cleanName(r.assessmentName)] as const));
  const assessmentId = new Map(assessmentNames.map((name) => [name, uuid(`assessment:${name}`)]));

  const participantQm = [...new Set(recs.map((r) => r.qmParticipantId))];
  const participantId = new Map(participantQm.map((id) => [id, uuid(`participant:${id}`)]));
  const pseudonym = new Map(recs.map((r) => [r.qmParticipantId, r.participantPseudonym] as const));

  // items: distinct per assessment, keyed by `${cleanName}|${qmQuestionId}`
  const itemKey = (clean: string, qm: string) => `${clean}|${qm}`;
  const itemId = new Map<string, string>();
  const itemMeta = new Map<string, CleanResponse>();
  for (const r of recs) {
    const clean = rawToClean.get(r.assessmentName)!;
    const k = itemKey(clean, r.qmQuestionId);
    if (!itemId.has(k)) {
      itemId.set(k, uuid(`item:${k}`));
      itemMeta.set(k, r);
    }
  }

  const out: string[] = [];
  const w = (s = "") => out.push(s);

  w(`-- ============================================================================`);
  w(`-- G12++ — demo cycle seed (pure SQL, fixed UUIDs)`);
  w(`-- Generated by scripts/build-seed-sql.mts from data/sample_qm_export.xlsx via`);
  w(`-- the real ingest + engine. item_stats and participant_scores are the GENUINE`);
  w(`-- computed values (engine ${ENGINE_VERSION}).`);
  w(`--`);
  w(`-- Paste this whole file into the Supabase SQL editor and Run. It needs at`);
  w(`-- least one auth user (Authentication → Users) — the FIRST user becomes the`);
  w(`-- cycle owner and is granted a lead_admin membership so they can open it.`);
  w(`-- To choose a specific owner, replace the two owner subqueries below.`);
  w(`--`);
  w(`-- Re-running: fixed UUIDs make this insert-once. To reseed, first run:`);
  w(`--   delete from exam_cycles where id = '${CYCLE_ID}';   -- cascades to all children`);
  w(`-- ============================================================================`);
  w();
  w(`begin;`);
  w();

  // 1. year + cycle + owner membership (0005: cycle is the MAY sitting of 2026)
  w(`-- 1. year + cycle (owner = first auth user) ---------------------------------`);
  w(`insert into exam_years (id, name, region, created_by) values`);
  w(`  ('${YEAR_ID}', '2026', 'eu-west', (select id from auth.users order by created_at limit 1));`);
  w();
  w(`insert into exam_cycles (id, name, status, region, created_by, year_id, sitting) values`);
  w(`  ('${CYCLE_ID}', 'May 2026', 'in_review', 'eu-west', (select id from auth.users order by created_at limit 1),`);
  w(`   '${YEAR_ID}', 'may');`);
  w();
  w(`insert into memberships (cycle_id, user_id, role)`);
  w(`  select '${CYCLE_ID}', id, 'lead_admin' from auth.users order by created_at limit 1;`);
  w();

  // 2. assessments
  w(`-- 2. assessments ------------------------------------------------------------`);
  const aValues = assessmentNames.map((name) => {
    const count = new Set(recs.filter((r) => rawToClean.get(r.assessmentName) === name).map((r) => r.qmQuestionId)).size;
    return `  ('${assessmentId.get(name)}', '${CYCLE_ID}', ${q(name)}, ${count}, 'in_review')`;
  });
  w(`insert into assessments (id, cycle_id, name, item_count, status) values`);
  w(aValues.join(",\n") + ";");
  w();

  // 3. participants
  w(`-- 3. participants -----------------------------------------------------------`);
  const pValues = participantQm.map(
    (qm) => `  ('${participantId.get(qm)}', '${CYCLE_ID}', ${q(qm)}, ${q(pseudonym.get(qm) ?? qm)})`,
  );
  w(`insert into participants (id, cycle_id, qm_participant_id, pseudonym_id) values`);
  w(pValues.join(",\n") + ";");
  w();

  // 4. items
  w(`-- 4. items ------------------------------------------------------------------`);
  const iValues: string[] = [];
  for (const [k, id] of itemId) {
    const m = itemMeta.get(k)!;
    const clean = rawToClean.get(m.assessmentName)!;
    iValues.push(
      `  ('${id}', '${CYCLE_ID}', '${assessmentId.get(clean)}', ${q(m.qmQuestionId)}, ${q(m.wording)}, ${q(m.majorElement)}, ${q(m.subElement)}, ${enumLit(m.demandLevel)}, ${q(m.itemSet)}, ${m.maxScore ?? 1}, 'active')`,
    );
  }
  emitInsert(w, `insert into items (id, cycle_id, assessment_id, qm_question_id, wording, major_element, sub_element, demand_level, item_set, max_score, status) values`, iValues, 200);
  w();

  // 5. responses
  w(`-- 5. responses (immutable facts) --------------------------------------------`);
  const rValues = recs.map((r) => {
    const clean = rawToClean.get(r.assessmentName)!;
    const pid = participantId.get(r.qmParticipantId)!;
    const iid = itemId.get(itemKey(clean, r.qmQuestionId))!;
    return `  ('${CYCLE_ID}', '${pid}', '${iid}', ${q(r.answerGiven)}, ${n(r.answerScore)}, ${n(r.responseTime)}, ${q(r.resultStatus)})`;
  });
  emitInsert(w, `insert into responses (cycle_id, participant_id, item_id, answer_given, answer_score, response_time, result_status) values`, rValues, 500);
  w();

  // 6. item_stats (engine) + 7/8 scores per assessment
  const statValues: string[] = [];
  const scoreRunValues: string[] = [];
  const scoreValues: string[] = [];

  for (const name of assessmentNames) {
    const aRecs = recs.filter((r) => rawToClean.get(r.assessmentName) === name);
    const aItemKeys = [...new Set(aRecs.map((r) => itemKey(name, r.qmQuestionId)))];
    const items: ItemMeta[] = aItemKeys.map((k) => {
      const m = itemMeta.get(k)!;
      return { itemId: itemId.get(k)!, assessmentId: assessmentId.get(name)!, wording: m.wording, majorElement: m.majorElement, subElement: m.subElement, demandLevel: m.demandLevel, maxScore: m.maxScore ?? 1 };
    });
    const responses: ResponseRecord[] = aRecs.map((r) => ({
      participantId: participantId.get(r.qmParticipantId)!,
      itemId: itemId.get(itemKey(name, r.qmQuestionId))!,
      assessmentId: assessmentId.get(name)!,
      score: r.answerScore,
    }));

    for (const s of engine.computeItemStats({ responses, items })) {
      statValues.push(
        `  ('${s.itemId}', ${n(s.pValue)}, ${enumLit(s.pRating)}, ${n(s.itemTotal)}, ${enumLit(s.itRating)}, ${n(s.pointBiserial)}, ${enumLit(s.pbRating)}, ${n(s.discrimination)}, ${enumLit(s.discRating)}, ${enumLit(s.overallReview)}, ${q(ENGINE_VERSION)})`,
      );
    }

    const runId = uuid(`scorerun:${name}`);
    scoreRunValues.push(`  ('${runId}', '${CYCLE_ID}', '${assessmentId.get(name)}', '{}'::uuid[], ${q(ENGINE_VERSION)})`);
    for (const sc of engine.computeScores(responses, [], { items })) {
      scoreValues.push(`  ('${runId}', '${sc.participantId}', '${assessmentId.get(name)}', ${n(sc.raw)}, ${n(sc.pct)}, ${sc.itemsSeen})`);
    }
  }

  w(`-- 6. item_stats (engine-computed) -------------------------------------------`);
  emitInsert(w, `insert into item_stats (item_id, p_value, p_rating, item_total, it_rating, point_biserial, pb_rating, discrimination, disc_rating, overall_review, engine_version) values`, statValues, 200);
  w();

  w(`-- 7. score_runs -------------------------------------------------------------`);
  w(`insert into score_runs (id, cycle_id, assessment_id, excluded_item_ids, engine_version) values`);
  w(scoreRunValues.join(",\n") + ";");
  w();

  w(`-- 8. participant_scores (engine-computed: MCQ-only — no essays/alterations) -`);
  emitInsert(w, `insert into participant_scores (score_run_id, participant_id, assessment_id, raw, pct, items_seen) values`, scoreValues, 500);
  w();

  // 9. grade_schemes — default boundaries (editable in the app)
  w(`-- 9. grade_schemes (default boundaries; adjust in the Boundaries screen) -----`);
  const gsValues: string[] = [];
  try {
    const mem = new InMemoryDataProvider();
    const live = mem.listCycles().find((c) => !c.mock) ?? mem.listCycles()[0];
    const memCycleId = live ? live.id : "may-2026";
    const scopes: { dbScope: string; memScope: string }[] = [
      { dbScope: "overall", memScope: "overall" },
      ...assessmentNames.map((name) => ({ dbScope: assessmentId.get(name)!, memScope: name })),
    ];
    for (const { dbScope, memScope } of scopes) {
      const m = mem.getBoundaries(memCycleId, memScope);
      if (!m) continue;
      const bands = m.levels.map((label, i) => ({
        label,
        min: i < m.cuts.length ? (m.cuts[i] ?? 0) : 0,
        max: i === 0 ? 100 : (m.cuts[i - 1] ?? 100),
      }));
      gsValues.push(`  ('${CYCLE_ID}', ${q(dbScope)}, 'judgemental', ${q(JSON.stringify(bands))}::jsonb)`);
    }
  } catch {
    // grade_schemes are optional — the app falls back to defaults if absent.
  }
  if (gsValues.length) {
    w(`insert into grade_schemes (cycle_id, scope, method, bands) values`);
    w(gsValues.join(",\n") + ";");
  } else {
    w(`-- (skipped — the app initialises default boundaries when none are stored)`);
  }
  w();

  w(`commit;`);
  w();
  w(`-- Done. ${assessmentNames.length} assessments, ${itemId.size} items, ${participantQm.length} participants,`);
  w(`-- ${recs.length} responses, ${statValues.length} item stats, ${scoreValues.length} participant scores.`);
  w();

  writeFileSync("supabase/seed.sql", out.join("\n"));
  console.log(
    `Wrote supabase/seed.sql — ${assessmentNames.length} assessments, ${itemId.size} items, ` +
      `${participantQm.length} participants, ${recs.length} responses, ${statValues.length} item_stats, ${scoreValues.length} scores.`,
  );
}

/** Emit a multi-row INSERT split into chunks of `size` value-rows per statement. */
function emitInsert(w: (s?: string) => void, header: string, values: string[], size: number) {
  if (values.length === 0) {
    w(`-- (none)`);
    return;
  }
  for (let i = 0; i < values.length; i += size) {
    const chunk = values.slice(i, i + size);
    w(header);
    w(chunk.join(",\n") + ";");
    if (i + size < values.length) w();
  }
}

main();
